### ISSUE TITLE
Task locking feature

### ISSUE THREAD

**Issue by jangorecki** [Bart6114/scheduleR#10]
Hi,
Any built-in support to detect file lock and not run the same script while it is still running?
My current cron task (non via scheduleR) is:
```ssh
flock -w 1 /tmp/scriptname.lockfile Rscript scriptname.R 2>> error_log.Rout 1>> cat_log.Rout
```
I wonder if you can support/improve/simplify it somehow? as it is quite critical feature.

**Comment by Bart6114** [comment]
@jangorecki, I agree that this can be a useful feature. It should be quite easy to implement. I'll have a look at it next week.

**Comment by Bart6114** [comment]
@jangorecki I tried to implement it (for tasks only at the moment). Default behaviour is that if a task is running (locked) no new instance will be started. This behaviour can be switched off to ignore the lock status (see the docs > tasks). A test is appreciated :)
