### ISSUE TITLE
Running report Error: Rscript ENONENT

### ISSUE THREAD

**Issue by samhalluk** [Bart6114/scheduleR#16]
When trying to run uploaded R scripts I'm getting Error: spawn Rscript Enoent.

syscall:'spawn Rscript'

My upload path is fine something to do with the RscriptExecutable in the user.config?

**Comment by bart6114** [comment]
I presume that the `RscriptExecutable`value is still `Rscript`?

What happens when you call `Rscript` from the terminal? Does it run? If not, make sure `Rscript` is on the `PATH`.

**Comment by samhalluk** [comment]
Hi,
Yes the RscriptExecutable is still the default of "Rscript".
No when i call Rscript from power shell terminal it doesn't run :( but the path is Rscript.
![enonent](https://cloud.githubusercontent.com/assets/9250243/8395947/9ffba886-1d86-11e5-91fe-438dc6a9e2a3.PNG)

**Comment by samhalluk** [comment]
Duhh I'm new to this...got to set the path for where the Rscript executable is located.

 "RscriptExecutable": "C:\Program Files\R\R-3.2.0\bin\x64\"

**Comment by samhalluk** [comment]
What about when running markdowns...

Error: self signed certificate in certificate chain?

I can feel I'm so close to getting full functionality ;)

**Comment by bart6114** [comment]
What happens when you open a console and enter `Rscript`? If you get an 'not found'-like error, `Rscript`'s directory is not in the [PATH variable](http://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them).

**Comment by samhalluk** [comment]
I've added Rscript to the path variable which is "C:\Users\name\AppData\Roaming\npm"
I've also added it to the root directory I'm running ScheduleR out of.

I can get the task running now but still getting the Self_signed_cert_in_chain error.

Is this because I am running on localhost?

**Comment by bart6114** [comment]
You should definitely not start copying the `Rscript` executable (which is what I understand from your comment).

Please open up a console windows, type `echo %path%` and let me know what the output is. Next, in the same console window, type `Rscript` and let me know what the output is.

**Comment by samhalluk** [comment]
Opening cmd and typing echo %path% gives...
![echo path](https://cloud.githubusercontent.com/assets/9250243/8456937/8d55f588-2006-11e5-9911-9b5884c84c8a.PNG)

And your right typing Rscript shows "system cannot find the path specified"

**Comment by samhalluk** [comment]
Ok sorted add R\R-3.2.0\bin to the path and now refer to the environment variable in the configuration json. Typing Rscript in the console now runs Rscript. However still getting self signed certificate error. Looks like a mail error.

**Comment by bart6114** [comment]
what is now the value of the `RscriptExecutable` in the `user.config.json`?

**Comment by samhalluk** [comment]
Simply "Rscript" now.

**Comment by bart6114** [comment]
hmm getting closer, but can't really place the certificate thing. can you try to schedule the `test_rmd_html.Rmd` file in the `/examples` folder to see what that gives?

**Comment by samhalluk** [comment]
thanks for your help! getting very close now!

I've scheduled test_rmd_html.Rmd and I now get  "The system cannot find the path specified." but running Rscript from the terminal works i.e. its in the path variable.

**Comment by bart6114** [comment]
did you specify the `uploadDir` in the user.config.json?

**Comment by samhalluk** [comment]
Yeah i just created a folder in the working directory called uploads and they go in there :)

**Comment by bart6114** [comment]
is pandoc installed?

**Comment by samhalluk** [comment]
I thought it was an optional dependency but I have installed it now..is there any other setup I need for pandoc?

**Comment by bart6114** [comment]
closing; old issue
