### ISSUE TITLE
No email capability so no new users

### ISSUE THREAD

**Issue by pofigster** [Bart6114/scheduleR#4]
I have ScheduleR in an environment where it cannot access the internet (but it can be accessed from the intranet).  I don't want to setup a mail server (in fact I don't know if I could) so I currently have no way of adding a user account.  Is there a manual process I can go through?  I'm happy to use MongoDB.

It's installed on Windows Server 2012.

**Comment by Bart6114** [comment]
Indeed, this should be addressed. I'll look into it this weekend.

**Comment by pofigster** [comment]
Awesome, thanks!

**Comment by Bart6114** [comment]
@pofigster I've added a quick dirty fix. If there is a error while sending the email with the user details the details (username + initial password) will be shown in the console (server-side). While definitely not ideal, it should give you some leeway in the short run. See below for an example.

![image](https://cloud.githubusercontent.com/assets/1965492/5891105/e9b18fc8-a481-11e4-9960-cd4802ea6c62.png)

If you've installed scheduleR by cloning the git repo a simple ```git pull``` should do the trick.
